'use server';
/**
 * @fileOverview Flow for the ApexBrain AI Offensive Orchestrator.
 * Wraps the Python-based attack planning logic.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';
import { execSync } from 'child_process';
import path from 'path';

const ApexBrainInputSchema = z.object({
  target: z.string().describe('The target IP or domain to analyze'),
});

const ApexBrainOutputSchema = z.object({
  plan: z.any().describe('The multi-phase attack plan generated by the AI'),
  summary: z.string().describe('A summary of the planned operations')
});

export async function getAttackPlan(input: z.infer<typeof ApexBrainInputSchema>) {
  return apexBrainFlow(input);
}

const apexBrainFlow = ai.defineFlow(
  {
    name: 'apexBrainFlow',
    inputSchema: ApexBrainInputSchema,
    outputSchema: ApexBrainOutputSchema,
  },
  async (input) => {
    const scriptPath = path.join(process.cwd(), 'ai-engine/offensive/apex_brain.py');
    
    try {
      const result = execSync(`python3 ${scriptPath} ${input.target}`).toString();
      const plan = JSON.parse(result);
      
      return {
        plan: plan,
        summary: `خطّة الهجوم لـ ${input.target} جاهزة سيدي القائد. تتضمن ${Object.keys(plan).length} مراحل قتالية.`
      };
    } catch (error) {
      return {
        plan: { error: "Failed to execute ApexBrain" },
        summary: "عذراً سيدي، حدث خطأ في استدعاء عقل الهجوم."
      };
    }
  }
);
